site_name: Site de documentation AUDC 

theme:
  name: material

nav:

  - Accueil: index.md
  - Source de données à AUDC: Readme.md
  - Interopérabilité de données en géomatique: Interoperabilite.md
  - ESRI et base de données PostgreSQL/PostGIS: esri.md
  



