site_name: Site de documentation g√©omatique üó∫Ô∏è

theme:
  name: readthedocs

nav:

  - Accueil: index.md
  - Source de donn√©es √† AUDC: Readme.md
  - Cycle de vie des donn√©es: cycle_de_vie_des_donnees.md
  - Interop√©rabilit√© de donn√©es en g√©omatique: Interoperabilite.md








