site_name: Site de documentation CPGEOM

theme:
  name: material

nav:

  - Accueil: index.md
  - Source de données à AUDC: Readme.md
  - Interopérabilité en géomatique: Interoperabilite.md
  - Cycle de vie des données: cycle_de_vie_des_donnees.md
  




