site_name: Site de documentation AUDC 

theme:
  name: material

nav:

  - Accueil: index.md
  - Source de données à AUDC: Readme.md
  - Cycle de vie des données: cycle_de_vie_des_donnees.md
  - Interopérabilité de données en géomatique: Interoperabilite.md



